name: Docker Image CI

on:
#  push:
#    tags:
#    - 'v*.*.*'
   push:
     branches:
     - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set most recent tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
    - uses: docker/login-action@v1
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: docker/build-push-action@v2.3.0
      name: Build and Push the Docker Image
      id: docker_build
      with:
        push: true
        tags: edenbox/schedules:latest
    
    - name: Docker Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set most recent tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Deploy the app to the cluster
      uses: nickgronow/kubectl@master
      with:
        config_data: ${{ secrets.KUBE_CONFIG_DATA }}
        args: set image deployment/schedule-app-deploy schedule-app=edenbox/schedules:${{ steps.vars.outputs.tag }} --namespace=schedule-app
        
    - name: Verify deployment
      uses: nickgronow/kubectl@master
      with:
        config_data: ${{ secrets.KUBE_CONFIG_DATA }}
        args: '"rollout status deployment/schedule-app-deploy --namespace=schedule-app"'
    
